version: "3.8"

networks:
  appnet:
    driver: bridge

services:
  kong:
    image: kong:3.9
    container_name: kong-oath2
    environment:
      KONG_DATABASE: "off"
      KONG_PROXY_LISTEN: "0.0.0.0:8000"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
      KONG_ADMIN_GUI_LISTEN: "0.0.0.0:8002"
      KONG_STATUS_LISTEN: "0.0.0.0:8100"
      KONG_ADMIN_GUI_PATH: /admin
    ports:
      - "8000"
      - "8001"
      - "8002"
      - "8100"
    networks: [appnet]

  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.6.0
    container_name: oauth2-proxy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      OAUTH2_PROXY_PROVIDER: oidc
      OAUTH2_PROXY_LOG_LEVEL: debug
      OAUTH2_PROXY_SCOPE: "openid profile email" # << fixed name + spaces
      OAUTH2_PROXY_OIDC_ISSUER_URL: ${OIDC_ISSUER}
      OAUTH2_PROXY_CLIENT_ID: ${OIDC_CLIENT_ID}
      OAUTH2_PROXY_CLIENT_SECRET: ${OIDC_CLIENT_SECRET}
      OAUTH2_PROXY_REDIRECT_URL: ${PUBLIC_ORIGIN}/oauth2/callback
      OAUTH2_PROXY_COOKIE_SECRET: ${OAUTH2_COOKIE_SECRET}

      OAUTH2_PROXY_OIDC_GROUPS_CLAIM: "resource_access.kong-client.roles"
      OAUTH2_PROXY_ALLOWED_GROUPS: ""

      OAUTH2_PROXY_REVERSE_PROXY: "true"
      OAUTH2_PROXY_SET_XAUTHREQUEST: "true"
      OAUTH2_PROXY_COOKIE_DOMAIN: host.docker.internal
      OAUTH2_PROXY_WHITELIST_DOMAINS: host.docker.internal:8086
      OAUTH2_PROXY_COOKIE_SAMESITE: lax
      OAUTH2_PROXY_COOKIE_SECURE: "false"
      OAUTH2_PROXY_HTTP_ADDRESS: 0.0.0.0:4180
      OAUTH2_PROXY_UPSTREAM: file:///dev/null
      OAUTH2_PROXY_EMAIL_DOMAINS: "*"
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: "true"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:4180/healthz"]
      interval: 5s
      timeout: 3s
      retries: 30
    networks: [appnet]

  oath2-admin-proxy:
    image: nginx:1.25-alpine
    container_name: oath2-admin-proxy
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8086:80"
    depends_on:
      oauth2-proxy:
        condition: service_started
    restart: unless-stopped
    networks: [appnet]
