
networks:
  kong-net:
    external: true
    name: kong-net

services:
  keycloak-db:
    image: postgres:16
    container_name: keycloak-db
    environment:
      POSTGRES_USER: ${KC_DB_USERNAME:-keycloak}
      POSTGRES_PASSWORD: ${KC_DB_PASSWORD:-keycloak}
      POSTGRES_DB: ${KC_DB_DATABASE:-keycloak}
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${KC_DB_USERNAME:-keycloak} -d ${KC_DB_DATABASE:-keycloak}"]
      interval: 5s
      timeout: 5s
      retries: 20
    networks:
      - kong-net

  keycloak:
    build: .
    container_name: keycloak
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      keycloak-db:
        condition: service_healthy
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_BOOTSTRAP_ADMIN_USERNAME:-admin}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_BOOTSTRAP_ADMIN_PASSWORD:-admin}
      KC_DB: postgres
      KC_DB_USERNAME: ${KC_DB_USERNAME:-keycloak}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD:-keycloak}
      KC_DB_URL_HOST: keycloak-db
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: ${KC_DB_DATABASE:-keycloak}
      KC_HTTP_ENABLED: "true"
      REALM_NAME: ${REALM_NAME:-demo}
      REALM_FILE: /opt/keycloak/data/import/demo-realm.json
      #RELATIVE PATH OF KEYCLOAK TO ADD IN ORIGINAL URL
      KC_HTTP_RELATIVE_PATH: /auth
      # Enable HTTPS
      #KC_HTTPS_CERTIFICATE_FILE: /etc/x509/https/tls.crt
      #KC_HTTPS_CERTIFICATE_KEY_FILE: /etc/x509/https/tls.key
      # ports
      #KC_HTTPS_PORT: 8446
      KC_HTTP_PORT: 8080
      # Host name / redirect config
      KC_PROXY: edge # respect X-Forwarded headers
      KC_HOSTNAME: host.docker.internal
      KC_HOSTNAME_PORT: 8080 # external port via Kong
      KEYCLOAK_FRONTEND_URL: "http://host.docker.internal:8080/auth"
    ports:
      - "${KEYCLOAK_HTTP_PORT}:8080"
    env_file:
      - ./.env
    command: ["start-dev", "--import-realm"]
    restart: unless-stopped
    volumes:
      - ./client.json:/opt/keycloak/data/import/client.json
     # - ./certs/keycloak.crt:/etc/x509/https/keycloak.crt
     # - ./certs/keycloak.key:/etc/x509/https/keycloak.key      -
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/host.docker.internal/8081; echo -e 'GET /auth/health/ready HTTP/1.1\\r\\nHost: host.docker.internal\\r\\nConnection: close\\r\\n\\r\\n' >&3; cat <&3 | grep '200 OK' || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 30
    networks:
      - kong-net

volumes:
  keycloak_db_data:
